apiVersion: v1
kind: PersistentVolume
metadata:
  name: PV-db
  labels:
    type: local
spec:
  storageClassName: voting-db
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"