apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ebs-db
  labels:
    type: cloud
spec:
  storageClassName: voting-db-ebs
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/data"
  awsElasticBlockStore:
    volumeID: vol-0fa9bfe3f29d6fe31
    fsType: ext4