apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ebs-db
  labels:
    type: cloud
spec:
  storageClassName: voting-db-ebs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-ebs-db