apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: db
  name: PVC-db
spec:
  storageClassName: voting-db
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi