apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: abdullahkimrigh/postgres-db:0.1
        name: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pv-ebs-db
      volumes:
      - name: pv-ebs-db
        persistentVolumeClaim:
          claimName: pvc-ebs-db
        awsElasticBlockStore:
          volumeID: vol-0fa9bfe3f29d6fe31
          fsType: ext4