apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: abdullahkimrigh/redis-app:0.1
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - mountPath: /var/lib/redis/data
          name: pv-ebs-db
      volumes:
      - name: pv-ebs-db
        persistentVolumeClaim:
          claimName: pvc-ebs-db